---

- name: Update repositories cache and install nfs-kernel-server
  apt: 
      name=nfs-kernel-server 
      #update_cache=yes cache_valid_time=3600
      
- name: Export "{{ nfs4.root_directory }}" in /etc/exports
  lineinfile: 
      dest: /etc/exports 
      backup: yes
      #regexp: "^{{ nfs4.root_directory }}" 
      line: "{{ nfs4.root_directory }} {{ nfs4.root_directory_export_option }}" 
      state: present
  register: nfs4_root_directory_export_result
  
- name: Create {{ nfs4.root_directory }}
  file: 
      path: "{{ nfs4.root_directory }}" 
      state: directory
  
- name: Ensure rpcbind is running
  service: 
      name: rpcbind 
      state: started 
      enabled: yes

- name: Restart NFS server service
  service: 
       name: nfs-kernel-server 
       state: restarted
  when: nfs4_root_directory_export_result|changed
  
- name: Create exported directories in, if the do not exist
  file: 
    path: "{{ item.export_path }}/{{ item.export_directory }}"
    state: directory
  with_items: nfs4.exports
  
- name: Create exported directories in {{ nfs4.root_directory }}
  file: 
    path: "{{ nfs4.root_directory }}/{{ item.export_directory }}"
    state: directory
  with_items: nfs4.exports
  
- name: Bind exported directories to {{ nfs4.root_directory }} in /etc/fstab
  lineinfile:
      dest: /etc/fstab
      backup: yes
      line: "{{ item.export_path }}/{{ item.export_directory }}  {{ nfs4.root_directory }}/{{ item.export_directory }}   none bind 0 0"
  with_items: nfs4.exports
  register: nfs4_directory_fstab_result
  
- name: Reload fstab
  command: mount -a
  when: nfs4_directory_fstab_result|changed
  
- name: Export shared directories
  lineinfile: 
      dest: /etc/exports 
      backup: yes
      line: "{{ nfs4.root_directory }}/{{ item.export_directory }}  {{ nfs4.shared_directory_export_option }}" 
  with_items: nfs4.exports
  register: nfs4_directory_export_result
    
- name: Restart NFS server service
  service: 
      name: nfs-kernel-server 
      state: restarted
  when: nfs4_directory_export_result|changed

- name: Check if NFS server service is started
  service: 
    name: nfs-kernel-server 
    state: started


