---

# Options for the NFSv4 pseudo-file system
nfs4:
# root directory with NFSv4 pseudo-file system
    root_directory: "/export"
    root_directory_export_option: "*(fsid=0,rw,insecure,no_subtree_check,async)"
# options for exported directories in /etc/export
    shared_directory_export_option: "*(rw,nohide,insecure,no_subtree_check,async)"
# Shared directories to export
    exports:
       - export_path: 
         export_directory: home
       - export_path: /opt
         export_directory: autoinstall
      